config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'pages#home'

  get 'pages/products', to: 'pages#products', as: 'products'
  get 'pages/employees', to: 'pages#employees', as: 'employees'
  get 'pages/impressum', to: 'pages#impressum', as: 'impressum'
  get 'pages/requests', to: 'pages#requests', as: 'requests'
  post 'pages/create', to: 'pages#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def products
  end

  def employees
  end

  def requests
  end

  def create
    @message = { firma: params[:firma], name: params[:name], number: params[:number], mail: params[:mail], message: params[:message] }
    MessageMailer.new_message(@message).deliver_now
    redirect_to requests_path
  end

  def impressum
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Opinc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('nut.webp')%>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/flashes" %>
    <div class="wrapper">
      <div class="container" style="margin-top: 100px; margin-bottom: 20px;color: #4B4E57;">
        <%= yield %>
      </div>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/employees.html.erb
<h2>Unsere Mitarbeiter</h2>
<hr>
<div class="d-flex justify-content-between mt-5 mb-5">
  <div class="employee-card">
    <div class="image-div opa"></div>
    <div class="people-info">
      <h4>Georg Opinc</h4>
      <p>Inhaber / Aussendienst</p>
      <p>Tel.: 0 74 24 / 93 15-11 <br> Fax: 0 74 24 / 93 15-20</p>
      <p>E-Mail: <%= mail_to 'g.opinc@opinc.de', 'g.opinc@opinc.de'%></p>
    </div>
  </div>
  <div class="employee-card">
    <div class="image-div ute">
    </div>
    <div class="people-info">
      <h4>Ute Opinc</h4>
      <p>Aussendienst</p>
      <p>Tel.: 0 74 24 / 93 15-13 <br> Fax: 0 74 24 / 93 15-20</p>
      <p>E-Mail: <%= mail_to 'u.opinc@opinc.de', 'u.opinc@opinc.de'%></p>
    </div>
  </div>
  <div class="employee-card">
    <div class="image-div oma">
    </div>
    <div class="people-info">
      <h4>Rosalinde Opinc</h4>
      <p>Buchhaltung</p>
      <p>Tel.: 0 74 24 / 93 15-14 <br> Fax: 0 74 24 / 93 15-20</p>
      <p>E-Mail: <%= mail_to 'r.opinc@opinc.de', 'r.opinc@opinc.de'%></p>
    </div>
  </div>
  <div class="employee-card">
    <div class="image-div volz">
    </div>
      <div class="people-info">
      <h4>Elisabeth Volz</h4>
      <p>Sekretariat</p>
      <p>Tel.: 0 74 24 / 93 15-0 <br> Fax: 0 74 24 / 93 15-20</p>
      <p>E-Mail: <%= mail_to 'e.volz@opinc.de', 'e.volz@opinc.de'%></p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div>
  <%= image_tag(asset_path('home_opinc.jpg'), style:"width: 100%;") %>
  <br><br><br><br><br>
  <div class="d-flex justify-content-between">
    <div class="home-divs">
      <h2 class="mb-4">Opinc Industrievertretung</h2>
      <p>Lang - u. Kurzdrehteile, Frästeile aus allen zerspanbaren Werkstoffen. Vom einfachen bis hochpräzisen Zeichnungsteil. Wir fertigen für Sie von der Nullserie bis hin zur Großserie.</p>
      <p>Wir sind spezialisiert auf die Vermittlung von Kundenspezifischen Zeichnungsteilen. </p>
      <p>Wir vertreten leistungsfähige Herstellter von: <br>Drehteilen, Frästeilen, Stanz- und Biegeteilen, Musterbau, Klein- und Großserien</p>
    </div>
    <div class="home-divs">
      <h2 class="mb-4">Wer sind wir?</h2>
      <p>Unser Kundenstamm setzt sich von Elektro-, Sanitär-, Automotiv, Möbel-, Medizintechnik, Beschläge, Maschinenbau und Fachkunden zusammen.</p>
      <p>Unsere Industrievertretung steht für, eine schnelle Verfügbarkeit, kompetente Beratung, fundiertes Fachwissen, motivierte und langjährige Mitarbeiter und jahrelange Erfahrung. </p>
      <p>Unser Ziel ist es eine gute und lange Partnerschaft  zwiwschen Hersteller und Kunden aufzubauen. <br>
        Lassen Sie uns und unsere Lieferwerke Kompetenz, Fachwissen und Leistungsfähigkeit unter Beweis stellen.</p>
    </div>
  </div>
  <br><br><br>
</div>

app/views/pages/impressum.html.erb
<div style="color: #4B4E57;">
  <h2>Impressum</h2>
  <hr>
  <h5>Angaben gemäß § 5 TMG:</h5>
  <p>Georg Opinc <br> Georg Opinc Industrievertretung <br> Max Plank Straße 34 <br> 78549 Spaichingen</p>
  <h5>Kontakt:</h5>
  <p>Telefon:	07424 - 93 15 0 <br>Telefax:	07424 - 93 15 20 <br> E-Mail:	info@opinc.de</p>
  <h5>Registereintrag:</h5>
  <p>Eintragung im Handelsregister. <br> Registergericht:Amtsgericht Spaichingen <br> Registernummer: HRA 399</p>
  <h5>Umsatzsteuer-ID:</h5>
  <p>Umsatzsteuer-Identifikationsnummer gemäß §27 a Umsatzsteuergesetz: <br> DE 429 020 46</p>
  <p>Quelle: http://www.e-recht24.de</p>
  <br>
  <h2>Datenschutzerklärung</h2>
  <hr>
  <p>Datenschutzerklärung für die Nutzung von Google Analytics <br>
  Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. ('Google').
  Google Analytics verwendet sog. "Cookies", Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse
  der Benutzung der Website durch Sie ermöglichen. Die durch den Cookie erzeugten Informationen über Ihre Benutzung dieser
  Website werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert. Im Falle der
  Aktivierung der IP-Anonymisierung auf dieser Webseite wird Ihre IP-Adresse von Google jedoch innerhalb von Mitgliedstaaten
  der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum zuvor gekürzt. <br>
  Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt.
  Im Auftrag des Betreibers dieser Website wird Google diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten,
  um Reports über die Websiteaktivitäten zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung
  verbundene Dienstleistungen gegenüber dem Websitebetreiber zu erbringen. Die im Rahmen von Google Analytics von Ihrem
  Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt. <br>
  Sie können die Speicherung der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern;
  wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website
  vollumfänglich werden nutzen können. Sie können darüber hinaus die Erfassung der durch das Cookie erzeugten und auf
  Ihre Nutzung der Website bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google
  verhindern, indem sie das unter dem folgenden Link verfügbare Browser-Plugin herunterladen und installieren:
  http://tools.google.com/dlpage/gaoptout?hl=de.</p>
</div>

app/views/pages/products.html.erb
<h2>Unsere Produkte</h2>
<hr>
<div>
  <div class="card-product" id="Dreh">
    <%= image_tag(asset_path('parts/drehteile.jpg')) %>
    <div class="card-product-infos">
      <h2>Drehteile</h2>
      <p>Product description with <strong>relevant info</strong> only.</p>
    </div>
  </div>
  <div class="card-product" id="Fraes">
    <%= image_tag(asset_path('parts/fraes.jpg')) %>
    <div class="card-product-infos">
      <h2>Frästeile</h2>
      <p>Product description with <strong>relevant info</strong> only.</p>
    </div>
  </div>
  <div class="card-product" id="Kaltform">
    <%= image_tag(asset_path('parts/kaltform.jpg')) %>
    <div class="card-product-infos">
      <h2>Kaltformteile</h2>
      <p>Product description with <strong>relevant info</strong> only.</p>
    </div>
  </div>
  <div class="card-product" id="Standard">
    <%= image_tag(asset_path('parts/standard.jpg')) %>
    <div class="card-product-infos">
      <h2>Standardteile</h2>
      <p>Product description with <strong>relevant info</strong> only.</p>
    </div>
  </div>
  <div class="card-product" id="Stanz">
    <%= image_tag(asset_path('parts/stanz.jpg')) %>
    <div class="card-product-infos">
      <h2>Stanzteile</h2>
      <p>Product description with <strong>relevant info</strong> only.</p>
    </div>
  </div>
  <div class="card-product" id="StanzBiege">
    <%= image_tag(asset_path('parts/stanzbiege.jpg')) %>
    <div class="card-product-infos">
      <h2>Stanz- und Biegeteile</h2>
      <p>Product description with <strong>relevant info</strong> only.</p>
    </div>
  </div>
  <div class="card-product" id="DrehStanzBiege">
    <%= image_tag(asset_path('parts/drehstanzbiege.jpg')) %>
    <div class="card-product-infos">
      <h2>Dreh-, Stanz- und Biegeteile</h2>
      <p>Product description with <strong>relevant info</strong> only.</p>
    </div>
  </div>
</div>

app/views/pages/requests.html.erb
<div>
  <h2>Immer für Sie erreichbar</h2>
  <hr>
  <br>
  <div class="d-flex justify-content-between">
    <div>
    <%= form_with url: "/pages/create", method: :post do |form| %>
      <div class="d-flex">
        <div>
          <%= form.text_field :firma, placeholder:"Firma", class:"form-styling" %><br>
          <%= form.text_field :name, placeholder:"Name, Vorname*", class:"form-styling"%><br>
          <%= form.text_field :number, placeholder:"Telefonnummer*", class:"form-styling" %><br>
          <%= form.text_field :mail, placeholder:"E-Mail*", class:"form-styling" %><br>
        </div>
        <div>
          <%= form.text_area :message, placeholder:"Ihre Nachricht an uns*", class:"form-styling-message" %><br><br>
        </div>
      </div>
      <%= form.submit "Nachricht senden", class:"btn-form" %>
    <% end %>
    </div>
    <div>
      <iframe src="https://storage.googleapis.com/maps-solutions-8reh7zpkcv/locator-plus/pjl1/locator-plus.html"
        width="500px" height="400px"
        style="border:0;"
        loading="lazy">
      </iframe>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex justify-content-between">
  <div>
    © 2014. Georg Opinc Industrievertretung
  </div>
  <div>
    Max-Plank-Straße 34, 78549 Spaichingen
  </div>
  <div>
    Tel: +49 (0) 7424 - 93 15 0
  </div>
   <div>
    Fax: +49 (0) 7424 - 93 15 20
  </div>
  <div>
    <%= mail_to 'info@opinc.de', 'info@opinc.de', style:"color: white;" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <div class="navbar-image-div">
        <%= image_tag asset_path('Georg_Opinc.png'), class:"navbar-image" %>
      </div>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "Startseite", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <div class="dropdown-toggle nav-link" role="button" id="navbarDropdown"data-bs-toggle="dropdown" aria-expanded="false">Produkte</div>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Drehteile", products_path(anchor: 'Dreh'), class: "dropdown-item" %>
            <%= link_to "Frästeile", products_path(anchor: 'Fraes'), class: "dropdown-item" %>
            <%= link_to "Kaltformteile", products_path(anchor: 'Kaltform'), class: "dropdown-item" %>
            <%= link_to "Standardteile", products_path(anchor: 'Standard'), class: "dropdown-item" %>
            <%= link_to "Stanzteil", products_path(anchor: 'Stanz'), class: "dropdown-item" %>
            <%= link_to "Stanz- und Biegeteile", products_path(anchor: 'StanzBiege'), class: "dropdown-item" %>
            <%= link_to "Dreh-, Stanz- und Biegeteile", products_path(anchor: 'DrehStanzBiege'), class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Mitarbeiter", employees_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Kontakt", requests_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Impressum", impressum_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</div>